config/routes.rb
Spending::Application.routes.draw do
<<<<<<< HEAD
  resources :users
  get "users/index"
 resources :posts

   root 'users#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
	

	validates :title, :content, :amount, :presence => true
	validates :title, :length => {:minimum => 2}
	validates :title, :uniqueness => true
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :name, :title, :amount, :presence => true
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


	def index
      @posts = Post.all
      @balance = 300
      @spendingtotal = @balance - Post.sum('amount')
	end

	def show
      @post = Post.find(params[:id])
	end

	def new
      @post = Post.new
	end

	def create
      @post = Post.new(post_params)

      if @post.save
        redirect_to posts_path, :notice => "Your post was saved"
      else
        render "new"
      end
	end

	def edit
      @post = Post.find(params[:id])
	end

	def update
      @post = Post.find(params[:id])

      if @post.update_attributes(post_params)
      	redirect_to posts_path, :notice => "Your post has been updated"
      else
      	render "edit"
      end
	end

	def destroy
      @post = Post.find(params[:id])
      @post.destroy
      redirect_to posts_path, :notice => "Your post has been deleted."
	end


	def post_params
      params.require(:post).permit(:title, :content, :amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@items = User.paginate(:page => params[:page], :per_page => 5)
    #@items = User.all
  	@users = User.where
  	@lewis = @items.find_all_by_name('Lewis', order: "created_at DESC")
  	lewisBalance = 1800.00
  	xueminBalance = 1800.00
  	@lewisSpent = lewisBalance - User.where(:name => 'Lewis').sum(:amount).round(2)
  	@xueminSpent = xueminBalance - User.where(:name => 'Xuemin').sum(:amount).round(2)
  	@xuemin = @items.find_all_by_name('Xuemin', order: "created_at DESC")
  end

  def new
  	@item = User.new
  end

  def create
  	@item = User.new(user_params)
  	if @item.save
    redirect_to '/', :notice => "Item added"
    else
      render 'new'
    end
  end
   


  def destroy
  	@item = User.find(params[:id])
  	@item.destroy
  	redirect_to users_path, :notice => "Your Item has been removed"
  end

  def show
  end

  def edit
  	@item = User.find(params[:id])
  end
  
  def update
  	@items = User.find(params[:id])
  	@items.update_attributes(user_params)
  	redirect_to '/'
  end

  private
  def user_params
    params.require(:user).permit(:name,:title,:details,:amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spending</title>
<<<<<<< HEAD
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="initial-scale=1, maximum-scale=1">



</head>
<body>
<nav class="navbar">
<%= link_to '', '/', class: 'fa fa-home' %>
<%= link_to ' Add New Item', new_user_path, class: 'btn' %>
</nav>
<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Posts</h1>

<%= form_for @post do |f| %>
<p>
  <%= f.label :title %><br />
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :content %><br />
  <%= f.text_area :content %>
</p>

<p>
  <%= f.label :amount %><br />
  <%= f.text_field :amount %>
</p>

<p>
  <%= f.submit "Update Post" %>
</p>

	<% end %>

app/views/posts/index.html.erb
<h1>Hello World</h1>
<p>Your Balance = <%= @spendingtotal %></p>

<% @posts.each do |post| %>
  <div class="postContainer">
    <p>Title: <%= link_to post.title, post %></p>
    <p>Content: <%= post.content %></p>
    <p>Amount: <%= post.amount %></p>
    <p><%= link_to "Edit", edit_post_path(post) %> |
       <%= link_to "Delete", post, :confirm => "Are you sure?", :method => :delete %>
    </p>
  </div>
<% end %>

<p><%= link_to "Add a New Post", new_post_path %>

app/views/posts/new.html.erb
<h1>Add a new post</h1>


<%= form_for @post do |f| %>
<p>
  <%= f.label :title %><br />
  <%= f.text_field :title %><br />
</p>

<p>
  <%= f.label :content %><br />
  <%= f.text_area :content %><br />
</p>

<p>
  <%= f.label :amount %><br />
  <%= f.text_field :amount %><br />
</p>

<p>
  <%= f.submit "Add a new Post" %>
</p>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.content %></p>
<p><%= @post.amount %></p>
<small><%= @post.created_at %></small>

app/views/users/_user_list.html.erb
 <div class="item"> 
          <div class="row text-right">
          <div class="item-title">
           <%= user.title.split.map(&:capitalize).join(' ') %>
           
           <%= link_to '', user, :confirm => "Are you sure you want to delete this?", :method => :delete, :class => 'fa fa-times float-right' %> 
	       <%= link_to '', edit_user_path(user), :class => "fa fa-pencil float-right" %>
	       <a href="javascript:void" class="info fa fa-info-circle float-right"></a>
          </div>
			
		   
	          <p>
		       <strong>Price:</strong> $<%= number_with_precision(user.amount, :precision => 2) %></p>

		       <p><strong>Posted:</strong> <%= user.updated_at.localtime.strftime("%d %b, %Y") %>
		       </p>
	       </div>

	       <div class="details">
		       <p><%= user.details %></p>
		    
	       </div>

	    </div>

app/views/users/edit.html.erb
<div class="container">
<div class="row">
<div class="col-md-9">
<h1>Edit Item</h1>

<%= form_for @item do |f| %>
<%= f.label :name %><br>
<%= f.text_field :name %><br>
<%= f.label :title %><br>
<%= f.text_field :title %><br>
<%= f.label :details %><br>
<%= f.text_area :details %><Br>
<%= f.label :amount %><br>
<%= f.text_field :amount %><br>
<p><%= f.submit "Update Item",  :class => 'btn btn-primary' %></p>
<% end %>
</div>
</div>
</div>

app/views/users/index.html.erb
<div class="container">


<div style="clear:both"></div>
<div class="column">
<h1>Lewis</h1>
<h2>Balance: $<%= number_with_precision(@lewisSpent, :precision => 2) %></h2>

	<% @lewis.each do |user| %>
	    
	   <%= render 'user_list', :user => user %>
 <% end %>
 <%= will_paginate @lewis, page_links: false, previous_label: '', next_label: '' %>
</div>



<div class="column">
  <h1>Xuemin</h1>
  <h2>Balance: $<%= number_with_precision(@xueminSpent, :precision => 2) %></h2>
	 
    <% @xuemin.each do |user| %>
      <%= render 'user_list', :user => user %>
	  <% end %>
	
	<%= will_paginate @xuemin, page_links: false, previous_label: '', next_label: '' %>
 </div>

</div> <!-- END CONTAINER -->

app/views/users/new.html.erb
<div class="container">
<h1>Add an Item</h1>

<%= form_for @item do |f| %>
  <p>
  <%= f.label :name %><br>
  <%= f.select :name, [['Lewis','Lewis'],['Xuemin','Xuemin']],:prompt => true %>
  </p>

  <p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
  </p>

  <p>
  <%= f.label :details %><br>
  <%= f.text_area :details %>
  </p>

  <p>
  <%= f.label :amount %><br>
  <%= f.text_field :amount %>
  </p>

  <p><%= f.submit 'Add Item' %></p>
<% end %>
</div>

<!-- <p><%= link_to "Home", '/' %></p> -->